import type { Database } from "@/lib/db";
import {
  emailConfigs,
  emailTemplates,
  outboundEmails,
  tickets,
  replies,
  products,
  agentProfiles,
  users,
  emailDispatches,
  emailReplyIntents,
} from "@/drizzle/schema";
import { eq, and, desc, isNotNull } from "drizzle-orm";
import { createProvider, type ProviderConfig } from "./providers";
import { getEnv } from "@/lib/db";
import { openEmailConfigSecrets } from "./config-secrets";
import {
  getDefaultBodyTemplate,
  getDefaultSubjectTemplate,
  renderEmailTemplate,
  sanitizeEmailTemplateHtml,
  type EmailTemplateType,
  type EmailTemplateVariables,
} from "@/lib/email-templates";
import { translatedReply, translatedTicketText } from "@/lib/tickets/translation";
import { assertAgentProduct, enqueueOutbound, usesMailAgent } from "./agent-outbox";

export interface SendEmailOptions {
  ticketId: string;
  templateType: EmailTemplateType;
  replyId?: string;
}

interface ConfiguredEmailMessage {
  to: string;
  subject: string;
  html: string;
  text?: string;
  headers?: Record<string, string>;
}

interface OutboundLinks {
  ticketId?: string;
  replyId?: string;
  notificationLogId?: string;
}

/**
 * Email clients load images without credentials, so relative attachment URLs
 * in rich reply HTML are absolutized against the public ToC origin.
 */
function publicTocOrigin(): string {
  const raw = (getEnv().TOC_DOMAINS as string | undefined) ?? "";
  const first = raw
    .split(",")
    .map((domain) => domain.trim())
    .filter(Boolean)[0];
  if (!first || first === "localhost" || first.startsWith("127.")) {
    return "http://localhost:3000";
  }
  return `https://${first}`;
}

function absolutizeAttachmentUrls(html: string): string {
  return html.replaceAll(
    'src="/api/attachments/',
    `src="${publicTocOrigin()}/api/attachments/`
  );
}

export type SendEmailResult = {
  success: boolean;
  queued?: boolean;
  emailId?: string;
  messageId?: string;
  error?: string;
};

/** Send and persist one attempt through a product's configured provider. */
export async function sendConfiguredEmail(
  db: Database,
  productId: string,
  message: ConfiguredEmailMessage,
  links: OutboundLinks = {}
): Promise<SendEmailResult> {
  const storedConfig = await db.query.emailConfigs.findFirst({
    where: eq(emailConfigs.productId, productId),
  });
  const config = storedConfig
    ? await openEmailConfigSecrets(storedConfig, getEnv().AUTH_SECRET, [
        "outboundApiKey",
        "outboundSmtpPass",
      ])
    : null;
  if (!config?.outboundEnabled || !config.outboundProvider) {
    return { success: false, error: "Outbound email not enabled for product" };
  }
  if (!config.outboundSenderEmail) {
    return { success: false, error: "Outbound sender email is not configured" };
  }
  assertAgentProduct(config.outboundSenderEmail, productId);

  const agent = usesMailAgent(config.outboundProvider, config.outboundSenderEmail);
  const emailId = agent && links.replyId ? `reply-${links.replyId}` : crypto.randomUUID();
  const now = new Date().toISOString();
  const text = message.text || htmlToText(message.html);
  const subject = message.subject.replace(/[\r\n]+/g, " ").trim().slice(0, 998);
  const threadMessageId = `<${crypto.randomUUID()}@onfire>`;
  const headers = {
    ...(message.headers ?? {}),
    ...(config.outboundProvider === "cloudflare" ? {} : { "Message-ID": threadMessageId }),
  };
  const insertEmail = db.insert(outboundEmails).values({
    id: emailId,
    productId,
    ticketId: links.ticketId || null,
    replyId: links.replyId || null,
    notificationLogId: links.notificationLogId || null,
    toEmail: message.to,
    fromEmail: config.outboundSenderEmail,
    fromName: config.outboundSenderName || "OnFire Support",
    subject,
    bodyHtml: message.html,
    bodyPlain: text,
    provider: config.outboundProvider,
    // Store the RFC identifier generated by OnFire. Provider queue IDs are
    // not guaranteed to be valid In-Reply-To/References values.
    providerMessageId: config.outboundProvider === "cloudflare" ? null : threadMessageId,
    status: agent ? "queued" : "pending",
    createdAt: now,
  }).onConflictDoNothing();

  if (agent) {
    await db.batch([
      insertEmail,
      db.insert(emailDispatches).values({ id: emailId, replyTo: config.outboundReplyTo, headers, createdAt: now }).onConflictDoNothing(),
      ...(links.replyId ? [db.delete(emailReplyIntents).where(eq(emailReplyIntents.replyId, links.replyId))] : []),
    ]);
    try {
      await enqueueOutbound(db, emailId);
    } catch (error) {
      // The committed outbox is repaired by cron even when the Queue is unavailable.
      console.error(JSON.stringify({ event: "email_enqueue_deferred", emailId, error: String(error) }));
    }
    return { success: true, queued: true, emailId };
  }
  await insertEmail;

  try {
    const provider = await createProvider({
      type: config.outboundProvider as ProviderConfig["type"],
      apiKey: config.outboundApiKey || undefined,
      smtpHost: config.outboundSmtpHost || undefined,
      smtpPort: config.outboundSmtpPort || undefined,
      smtpUser: config.outboundSmtpUser || undefined,
      smtpPassword: config.outboundSmtpPass || undefined,
    });
    const result = await provider.send({
      to: message.to,
      from: config.outboundSenderEmail,
      fromName: config.outboundSenderName || "OnFire Support",
      replyTo: config.outboundReplyTo || undefined,
      subject,
      html: message.html,
      text,
      headers,
    });
    await db
      .update(outboundEmails)
      .set({
        status: result.success ? "sent" : "failed",
        providerMessageId: result.success ? (config.outboundProvider === "cloudflare" ? result.messageId ?? null : threadMessageId) : null,
        errorMessage: result.error?.slice(0, 2_000) || null,
        sentAt: result.success ? new Date().toISOString() : null,
      })
      .where(eq(outboundEmails.id, emailId));
    return result;
  } catch (error) {
    const errorMessage =
      error instanceof Error
        ? error.message.slice(0, 2_000)
        : "Unknown email provider error";
    await db
      .update(outboundEmails)
      .set({ status: "failed", errorMessage })
      .where(eq(outboundEmails.id, emailId));
    return { success: false, error: errorMessage };
  }
}

/**
 * Send an arbitrary email through the product's configured outbound
 * provider. Used by the "email" notification channel (agent alerts);
 * customer-facing ticket mail goes through `sendTicketNotification`.
 */
export async function sendNotificationEmail(
  db: Database,
  productId: string,
  message: { to: string; subject: string; html: string },
  notificationLogId?: string,
): Promise<SendEmailResult> {
  return sendConfiguredEmail(db, productId, message, { notificationLogId });
}

export async function sendTicketNotification(
  db: Database,
  options: SendEmailOptions
): Promise<SendEmailResult> {
  const { ticketId, templateType, replyId } = options;

  // Get ticket
  const ticket = await db.query.tickets.findFirst({
    where: eq(tickets.id, ticketId),
  });

  if (!ticket) {
    return { success: false, error: `Ticket not found: ${ticketId}` };
  }

  // Anonymous customers (externalId-only identity) have no email channel.
  if (!ticket.customerEmail) {
    return { success: false, error: "Customer has no email address" };
  }
  const customerEmail = ticket.customerEmail;

  // Get template for this event type (fall back to built-in defaults)
  const template = await db.query.emailTemplates.findFirst({
    where: and(
      eq(emailTemplates.productId, ticket.productId),
      eq(emailTemplates.templateType, templateType),
      eq(emailTemplates.enabled, true)
    ),
  });

  // Get product name
  const product = await db.query.products.findFirst({
    where: eq(products.id, ticket.productId),
  });

  // Get reply content if applicable
  let replyContent = "";
  let replyContentHtml = "";
  let agentName = "";
  if (replyId) {
    const reply = await db.query.replies.findFirst({
      where: eq(replies.id, replyId),
    });
    if (reply) {
      const projected = translatedReply(
        reply,
        ticket.customerLanguage ?? product?.defaultLanguage ?? "en"
      );
      replyContent = projected.content;
      replyContentHtml = projected.contentHtml ?? "";
      if (reply.senderId) {
        const profile = await db.query.agentProfiles.findFirst({
          where: eq(agentProfiles.userId, reply.senderId),
        });
        if (profile) {
          agentName = profile.displayName;
        } else {
          const user = await db.query.users.findFirst({
            where: eq(users.id, reply.senderId),
          });
          agentName = user?.displayName || "";
        }
      }
    }
  }

  // Build email content
  const variables: EmailTemplateVariables = {
    ticket_id: ticket.id,
    subject: translatedTicketText(
      ticket,
      ticket.customerLanguage ?? product?.defaultLanguage ?? "en",
      "subject"
    ),
    customer_name: customerEmail.split("@")[0],
    customer_email: customerEmail,
    agent_name: agentName,
    reply_content: replyContent,
    product_name: product?.name || "",
  };

  const subjectTemplate =
    template?.subjectTemplate || getDefaultSubjectTemplate(templateType);
  const bodyTemplate =
    template?.bodyTemplate || getDefaultBodyTemplate(templateType);

  const subject = renderEmailTemplate(subjectTemplate, variables, { html: false });
  const bodyHtml = renderEmailTemplate(
    sanitizeEmailTemplateHtml(bodyTemplate),
    variables,
    {
      html: true,
      // Stored reply HTML is already sanitized (sanitizeRichHtml); inject it
      // verbatim so rich agent replies keep their formatting in emails.
      trustedHtml: replyContentHtml
        ? { reply_content: absolutizeAttachmentUrls(replyContentHtml) }
        : undefined,
    }
  );
  const previousMessages = await db
    .select({ providerMessageId: outboundEmails.providerMessageId })
    .from(outboundEmails)
    .where(
      and(
        eq(outboundEmails.ticketId, ticket.id),
        eq(outboundEmails.status, "sent"),
        isNotNull(outboundEmails.providerMessageId)
      )
    )
    .orderBy(desc(outboundEmails.createdAt))
    .limit(1);
  const headers = buildThreadHeaders(previousMessages[0]?.providerMessageId);

  const result = await sendConfiguredEmail(
    db,
    ticket.productId,
    { to: customerEmail, subject, html: bodyHtml, headers },
    { ticketId: ticket.id, replyId }
  );
  if (result.success && !result.queued && replyId) {
    await db
      .update(replies)
      .set({ emailSent: true })
      .where(eq(replies.id, replyId));
  }
  return result;
}

/** Build bounded RFC thread headers from a provider's last message id. */
export function buildThreadHeaders(
  messageId: string | null | undefined
): Record<string, string> | undefined {
  const trimmed = messageId?.trim();
  if (!trimmed || /\r|\n/.test(trimmed) || trimmed.length > 998) {
    return undefined;
  }
  const bare = trimmed.replace(/^</, "").replace(/>$/, "");
  if (!bare || /[<>\s]/.test(bare)) return undefined;
  const normalized = `<${bare}>`;
  return {
    "In-Reply-To": normalized,
    References: normalized,
  };
}

export function htmlToText(html: string): string {
  return html
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/(p|div|li|h[1-6]|blockquote)>/gi, "\n")
    .replace(/<[^>]*>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}
