/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/email-agent/wrangler.jsonc --config=wrangler.jsonc --env-file=wrangler.types.env --include-runtime=false --env-interface=MailAgentEnv workers/email-agent/worker-configuration.d.ts` (hash: 6109f234a7141de9d49ba0e3340c48e7)
interface __BaseEnv_MailAgentEnv {
	EMAIL_STORAGE: R2Bucket;
	SEND_EMAIL: SendEmail;
	EMAIL_INBOUND_QUEUE: Queue;
	EMAIL_AGENT_ADDRESSES: "support@example.com";
	MAIN_MAIL: Service<typeof import("../../worker").MailAgentGateway>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_MailAgentEnv {}
}
interface MailAgentEnv extends __BaseEnv_MailAgentEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EMAIL_AGENT_ADDRESSES">> {}
}
