name = "onfire-toc-worker"
main = "src/index.ts"
compatibility_date = "2025-06-01"
node_compat = true

[vars]
APP_PREFIX = "/api/toc"

[[d1_databases]]
binding = "DB"
database_name = "onfire-d1"
database_id = "local"

