name = "onfire-toc-worker"
main = "src/index.ts"
compatibility_date = "2025-12-31"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_PREFIX = "/api/toc"

[[d1_databases]]
binding = "DB"
database_name = "onfire-d1"
database_id = "REPLACE_WITH_D1_ID"

