/**
 * Custom worker entry: wraps the OpenNext-generated handler and adds
 *  - a `scheduled` handler for cron triggers (SLA scanning / auto-close)
 *  - an `email` handler for Cloudflare Email Routing (inbound support mail)
 *
 * Both fire a self-request through the WORKER_SELF_REFERENCE service binding
 * so the work runs inside a normal request context (D1, caches and the
 * OpenNext async-local storage all behave as in a regular request).
 */
// @ts-ignore — generated by `opennextjs-cloudflare build` before deploy
import openNextHandler from "./.open-next/worker.js";
import PostalMime from "postal-mime";
// workerd-only module; resolved natively by wrangler when bundling this entry.
// Exposed via globalThis for code living inside the Next server bundle
// (which cannot import `cloudflare:` schemes) — see services/email/providers/smtp.ts.
import { connect } from "cloudflare:sockets";
import {
  isTocProxyAllowedOnSurface,
  isTocProxyStaticAsset,
  rewriteTocProxyRequest,
  rewriteTocProxyResponse,
  stripTocProxyPrefix,
} from "./src/lib/toc-proxy";
import { TOC_PROXY_PREFIX } from "./src/lib/toc-path";
import { classifySurface, isApiAllowedOnSurface } from "./src/lib/surface-routing";
import { readResponseText } from "./src/lib/response-body";

(globalThis as Record<string, unknown>).__cfSocketsConnect = connect;

// These bindings are required by the custom entrypoint even though Wrangler's
// generated interface marks optional bindings as possibly absent.
type WorkerEnv = CloudflareEnv &
  Required<Pick<CloudflareEnv, "ASSETS" | "WORKER_SELF_REFERENCE">>;

/** Extract spf/dkim verdicts from an Authentication-Results header. */
function parseAuthResults(header: string | null): {
  spfResult?: string;
  dkimResult?: boolean;
} {
  if (!header) return {};
  const value = header.toLowerCase();
  const spf = value.match(/spf=([a-z]+)/)?.[1];
  const dkim = value.match(/dkim=([a-z]+)/)?.[1];
  return {
    spfResult: spf,
    dkimResult: dkim ? dkim === "pass" : undefined,
  };
}

const MAX_INBOUND_BYTES = 10 * 1024 * 1024;

export default {
  async fetch(request: Request, env: WorkerEnv, ctx: ExecutionContext) {
    const url = new URL(request.url);
    const surface = classifySurface(url.host, {
      adminDomains: env.ADMIN_DOMAINS,
      tocDomains: env.TOC_DOMAINS,
      development:
        typeof process !== "undefined" && process.env.NODE_ENV === "development",
    });
    if (
      url.pathname === TOC_PROXY_PREFIX ||
      url.pathname.startsWith(`${TOC_PROXY_PREFIX}/`)
    ) {
      const strippedPath = stripTocProxyPrefix(url.pathname);
      if (strippedPath === null) {
        return new Response("Not found", { status: 404 });
      }
      if (!isTocProxyAllowedOnSurface(strippedPath, surface)) {
        return new Response("Not found", { status: 404 });
      }
      const rewritten = rewriteTocProxyRequest(request);
      if (!rewritten) return new Response("Not found", { status: 404 });
      const isStaticAsset = isTocProxyStaticAsset(strippedPath);
      const response = isStaticAsset
        ? await env.ASSETS.fetch(rewritten)
        : await openNextHandler.fetch(rewritten, env, ctx);
      return rewriteTocProxyResponse(request, response);
    }
    // The marker is internal to this Worker; never trust a client-provided one.
    if (request.headers.has("x-onfire-proxy-prefix")) {
      const headers = new Headers(request.headers);
      headers.delete("x-onfire-proxy-prefix");
      request = new Request(request, { headers });
    }
    if (!isApiAllowedOnSurface(url.pathname, surface)) {
      return new Response("Not found", { status: 404 });
    }
    return openNextHandler.fetch(request, env, ctx);
  },

  async scheduled(
    _controller: ScheduledController,
    env: WorkerEnv,
    ctx: ExecutionContext
  ) {
    ctx.waitUntil(
      env.WORKER_SELF_REFERENCE.fetch(
        "https://internal/api/toc/tasks/sla-scan",
        {
          method: "POST",
          headers: { authorization: `Bearer ${env.AUTH_SECRET}` },
        }
      ).then(async (res) => {
        if (!res.ok) {
          console.error(
            JSON.stringify({
              event: "sla_scan_failed",
              status: res.status,
              detail: await readResponseText(res, 4_096),
            })
          );
        }
      })
    );
  },

  /**
   * Cloudflare Email Routing entry point. Configure a route (or catch-all)
   * pointing at this worker; the message is parsed and pushed through the
   * standard inbound pipeline (spam check → reply detection → AI filter).
   */
  async email(
    message: ForwardableEmailMessage,
    env: WorkerEnv,
    _ctx: ExecutionContext
  ) {
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(message.from)) {
      message.setReject("A valid sender address is required");
      return;
    }
    if (message.rawSize > MAX_INBOUND_BYTES) {
      message.setReject("Message exceeds the 10 MiB inbound limit");
      return;
    }

    let parsed;
    try {
      const raw = await new Response(message.raw).arrayBuffer();
      parsed = await PostalMime.parse(raw);
    } catch (error) {
      console.error(
        JSON.stringify({
          event: "inbound_email_parse_failed",
          from: message.from,
          to: message.to,
          error: error instanceof Error ? error.message : String(error),
        })
      );
      message.setReject("Message could not be parsed");
      return;
    }

    const auth = parseAuthResults(message.headers.get("authentication-results"));
    const payload = {
      provider: "cloudflare" as const,
      // Envelope MAIL FROM is supplied by the SMTP transport. The From header
      // is display metadata and can be spoofed, so never use it as identity.
      fromEmail: message.from,
      fromName: parsed.from?.name || undefined,
      toEmail: message.to,
      subject: parsed.subject || "(no subject)",
      bodyPlain: parsed.text || undefined,
      bodyHtml: parsed.html || undefined,
      messageId:
        parsed.messageId || message.headers.get("message-id") || undefined,
      inReplyTo: message.headers.get("in-reply-to") || undefined,
      references: message.headers.get("references") || undefined,
      ...auth,
    };

    const res = await env.WORKER_SELF_REFERENCE.fetch(
      "https://internal/api/toc/tasks/inbound-email",
      {
        method: "POST",
        headers: {
          authorization: `Bearer ${env.AUTH_SECRET}`,
          "content-type": "application/json",
        },
        body: JSON.stringify(payload),
      }
    );

    if (!res.ok) {
      const detail = await readResponseText(res, 4_096);
      console.error(
        JSON.stringify({
          event: "inbound_email_processing_failed",
          status: res.status,
          from: message.from,
          to: message.to,
          detail,
        })
      );
      // setReject() is a permanent SMTP failure. Throwing lets Cloudflare
      // surface a transient processing failure instead of silently dropping
      // a valid support request.
      throw new Error(`Inbound email processing failed (${res.status})`);
    }
  },
} satisfies ExportedHandler<WorkerEnv>;
