/**
 * Custom worker entry: wraps the OpenNext-generated handler and adds a
 * `scheduled` handler for cron triggers (SLA scanning / auto-close).
 *
 * The cron fires a self-request through the WORKER_SELF_REFERENCE service
 * binding so the task runs inside a normal request context (D1, caches and
 * the OpenNext async-local storage all behave as in a regular request).
 */
// @ts-ignore — generated by `opennextjs-cloudflare build` before deploy
import openNextHandler from "./.open-next/worker.js";

interface Env extends CloudflareEnv {
  WORKER_SELF_REFERENCE: Fetcher;
}

export default {
  fetch: (request: Request, env: Env, ctx: ExecutionContext) =>
    openNextHandler.fetch(request, env, ctx),

  async scheduled(
    _controller: ScheduledController,
    env: Env,
    ctx: ExecutionContext
  ) {
    ctx.waitUntil(
      env.WORKER_SELF_REFERENCE.fetch(
        "https://internal/api/toc/tasks/sla-scan",
        {
          method: "POST",
          headers: { authorization: `Bearer ${env.AUTH_SECRET}` },
        }
      ).then(async (res) => {
        if (!res.ok) {
          console.error(`SLA scan failed: ${res.status} ${await res.text()}`);
        }
      })
    );
  },
} satisfies ExportedHandler<Env>;
