/**
 * Custom worker entry: wraps the OpenNext-generated handler and adds
 *  - a `scheduled` handler for cron triggers (SLA scanning / auto-close)
 *  - an `email` handler for Cloudflare Email Routing (inbound support mail)
 *
 * Email is durably spooled to R2 and Queues. Consumers and cron fire a self-request through the WORKER_SELF_REFERENCE service binding
 * so the work runs inside a normal request context (D1, caches and the
 * OpenNext async-local storage all behave as in a regular request).
 */
// @ts-ignore — generated by `opennextjs-cloudflare build` before deploy
import openNextHandler from "./.open-next/worker.js";
import { WorkerEntrypoint } from "cloudflare:workers";
import { enqueueInboundEmail, inboundQueueMessage, queueRetryDelay, repairInboundEnqueue } from "./src/lib/email-queue";
import { deliveryReceiptSchema, type DeliveryReceipt, type OutboundClaim } from "./src/lib/email-agent-contract";
// workerd-only module; resolved natively by wrangler when bundling this entry.
// Exposed via globalThis for code living inside the Next server bundle
// (which cannot import `cloudflare:` schemes) — see services/email/providers/smtp.ts.
import { connect } from "cloudflare:sockets";
import {
  isTocProxyAllowedOnSurface,
  isTocProxyStaticAsset,
  rewriteTocProxyRequest,
  rewriteTocProxyResponse,
  stripTocProxyPrefix,
} from "./src/lib/toc-proxy";
import { TOC_PROXY_PREFIX } from "./src/lib/toc-path";
import { classifySurface, isApiAllowedOnSurface } from "./src/lib/surface-routing";
import { readResponseText } from "./src/lib/response-body";

(globalThis as Record<string, unknown>).__cfSocketsConnect = connect;

// These bindings are required by the custom entrypoint even though Wrangler's
// generated interface marks optional bindings as possibly absent.
type WorkerEnv = CloudflareEnv &
  Required<Pick<CloudflareEnv, "ASSETS" | "WORKER_SELF_REFERENCE">>;

async function mailTask<T>(env: WorkerEnv, payload: unknown): Promise<T> {
  const response = await env.WORKER_SELF_REFERENCE.fetch("https://internal/api/toc/tasks/email-agent", {
    method: "POST", headers: { authorization: `Bearer ${env.AUTH_SECRET}`, "content-type": "application/json" },
    body: JSON.stringify(payload),
  });
  if (!response.ok) throw new Error(`Mail task failed (${response.status}): ${await readResponseText(response, 2048)}`);
  const body = await response.json() as { data: T };
  return body.data;
}

/** Capability-scoped service binding; the agent never receives AUTH_SECRET or a D1 binding. */
export class MailAgentGateway extends WorkerEntrypoint<WorkerEnv> {
  async claim(id: string): Promise<OutboundClaim> {
    if (typeof id !== "string" || !id || id.length > 128) throw new Error("Invalid outbound id");
    return mailTask(this.env, { action: "claim", id });
  }
  async complete(input: DeliveryReceipt): Promise<void> {
    const receipt = deliveryReceiptSchema.parse(input);
    await mailTask(this.env, { action: "complete", receipt });
  }
}

export default {
  async fetch(request: Request, env: WorkerEnv, ctx: ExecutionContext) {
    const url = new URL(request.url);
    const surface = classifySurface(url.host, {
      adminDomains: env.ADMIN_DOMAINS,
      tocDomains: env.TOC_DOMAINS,
      development:
        typeof process !== "undefined" && process.env.NODE_ENV === "development",
    });
    if (
      url.pathname === TOC_PROXY_PREFIX ||
      url.pathname.startsWith(`${TOC_PROXY_PREFIX}/`)
    ) {
      const strippedPath = stripTocProxyPrefix(url.pathname);
      if (strippedPath === null) {
        return new Response("Not found", { status: 404 });
      }
      if (!isTocProxyAllowedOnSurface(strippedPath, surface)) {
        return new Response("Not found", { status: 404 });
      }
      const rewritten = rewriteTocProxyRequest(request);
      if (!rewritten) return new Response("Not found", { status: 404 });
      const isStaticAsset = isTocProxyStaticAsset(strippedPath);
      const response = isStaticAsset
        ? await env.ASSETS.fetch(rewritten)
        : await openNextHandler.fetch(rewritten, env, ctx);
      return rewriteTocProxyResponse(request, response);
    }
    // The marker is internal to this Worker; never trust a client-provided one.
    if (request.headers.has("x-onfire-proxy-prefix")) {
      const headers = new Headers(request.headers);
      headers.delete("x-onfire-proxy-prefix");
      request = new Request(request, { headers });
    }
    if (!isApiAllowedOnSurface(url.pathname, surface)) {
      return new Response("Not found", { status: 404 });
    }
    return openNextHandler.fetch(request, env, ctx);
  },

  async scheduled(
    _controller: ScheduledController,
    env: WorkerEnv,
    ctx: ExecutionContext
  ) {
    ctx.waitUntil(mailTask(env, { action: "repair" }).catch(error => console.error("Mail outbox repair failed:", error)));
    ctx.waitUntil(repairInboundEnqueue(env.EMAIL_STORAGE, env.EMAIL_INBOUND_QUEUE).catch(error => console.error("Mail ingress repair failed:", error)));
    ctx.waitUntil(
      env.WORKER_SELF_REFERENCE.fetch(
        "https://internal/api/toc/tasks/sla-scan",
        {
          method: "POST",
          headers: { authorization: `Bearer ${env.AUTH_SECRET}` },
        }
      ).then(async (res) => {
        if (!res.ok) {
          console.error(
            JSON.stringify({
              event: "sla_scan_failed",
              status: res.status,
              detail: await readResponseText(res, 4_096),
            })
          );
        }
      })
    );
  },

  async email(message: ForwardableEmailMessage, env: WorkerEnv) {
    await enqueueInboundEmail(message, env.EMAIL_STORAGE, env.EMAIL_INBOUND_QUEUE, "main");
  },

  async queue(batch: MessageBatch<unknown>, env: WorkerEnv) {
    for (const message of batch.messages) {
      try {
        const job = inboundQueueMessage.parse(message.body);
        await mailTask(env, { action: "inbound", message: job });
        message.ack();
      } catch (error) {
        console.error(JSON.stringify({ event: "queued_inbound_failed", messageId: message.id, error: String(error) }));
        message.retry({ delaySeconds: queueRetryDelay(message.attempts) });
      }
    }
  },
} satisfies ExportedHandler<WorkerEnv>;
